{
    "types" : {
        "Press" : {
            pluralLabel: "Press",
        "Team Meeting" : {
            pluralLabel: "Team Meetings",
        "Dev Meeting" : {
            pluralLabel: "Dev Meetings",
        "Design Meeting" : {
            pluralLabel: "Design Meetings",
        "Test Event" : {
            pluralLabel: "Test Events",
        "Event" : {
            pluralLabel: "Events",
        "Hackathon" : {
            pluralLabel: "Hackathons",
        "Project Release" : {
            pluralLabel: "Project Releases",
        "Conference" : {
            pluralLabel: "Conferences"
        }
        }
        }
        }
        }
        }
        }
        }
        }
    },
    "properties": {
        "person" : {
            "valueType" : "item"
        }
    },
    "items" : [
//HACKATHONS
        {   "type" :                  "Hackathon",
            "label" :                 "STEM Video Game Challenge Hackathon '12",
            "discipline" :            "Hackathon",
            "date" :                  "2012-02-02",
            "relationship" :          "Hackathon",
            "relationship-detail" :   "Hackathon to garner interest and entrants for National STEM Video Game Challenge",
            "imageURL" :              "hackfest.png",
            "url" :                   "http://foss.rit.edu/stem12"
        },
        {   "type" :                  "Hackathon",
            "label" :                 "STEM Video Game Challenge Hackathon '11",
            "discipline" :            "Hackathon",
            "date" :                  "2011-12-15",
            "relationship" :          "Hackathon",
            "relationship-detail" :   "Hackathon to garner interest and entrants for National STEM Video Game Challenge",
            "imageURL" :              "hackfest.png",
            "url" :                   "http://foss.rit.edu/stem11"
        },
        {   "type" :                  "Hackathon",
            "label" :                 "Election Night Hackathon '11",
            "discipline" :            "Hackathon",
            "date" :                  "2011-11-08",
            "relationship" :          "Hackathon",
            "relationship-detail" :   "Open event to watch real-time results of the election, and hack on open projects",
            "imageURL" :              "hackfest.png",
            "url" :                   "http://foss.rit.edu/election-night-hackathon-2011"
        },
        {   "type" :                  "Hackathon",
            "label" :                 "Software Freedom Day '11",
            "discipline" :            "Hackathon",
            "date" :                  "2011-09-17",
            "relationship" :          "Hackathon",
            "relationship-detail" :   "Open Hackathon and Lightning Talks ",
            "imageURL" :              "hackfest.png",
            "url" :                   "http://softwarefreedomday.org"
        },
        {   "type" :                  "Hackathon",
            "label" :                 "CrisisCampRoc Hackathon for Haiti",
            "discipline" :            "Hackathon",
            "date" :                  "2010-02-12",
            "relationship" :          "Hackathon",
            "relationship-detail" :   "Hackathon for Haiti relief",
            "imageURL" :              "hackfest.png",
            "url" :                   "http://pages.e-democracy.org/DemocracyMap"
        },
        {   "type" :                  "Hackathon",
            "label" :                 "DemocracyMaps Dev Camp Hackathon",
            "discipline" :            "Hackathon",
            "date" :                  "2010-06-14",
            "relationship" :          "Hackathon",
            "relationship-detail" :   "DemocracyMaps Dev Camp Hackathon",
            "imageURL" :              "hackfest.png",
            "url" :                   "http://www.rit.edu/innovationcenter/crisiscamproc-hack-thon-haiti-follow"
        },
        {   "type" :                  "Hackathon",
            "label" :                 "Sunlight Foundation's Great American Hackathon",
            "discipline" :            "Hackathon",
            "date" :                  "2009-12-12",
            "relationship" :          "Hackathon",
            "relationship-detail" :   "RIT's local hackathon as a part of the Great American Hackathon event",
            "imageURL" :              "hackfest.png",
            "url" :                   "http://www.rit.edu/innovationcenter/great-american-hackathon-rit"
        },
        {   "type" :                  "Hackathon",
            "label" :                 "FOSS@RIT OLPC HQ Hackathon",
            "discipline" :            "Hackathon",
            "date" :                  "2010-07-28",
            "relationship" :          "Hackathon",
            "relationship-detail" :   "FOSS@RIT goes to OLPC HQ!",
            "imageURL" :              "hackfest.png",
            "url" :                   "http://www.rit.edu/innovationcenter/category/tags/hackathon"
        },
        {   "type" :                  "Hackathon",
            "label" :                 "FOSS@RIT Homestretch Hackathon Summer",
            "discipline" :            "Hackathon",
            "date" :                  "2010-08-04",
            "relationship" :          "Hackathon",
            "relationship-detail" :   "FOSS@RIT Homestretch Hackathon",
            "imageURL" :              "hackfest.png",
            "url" :                   "http://foss.rit.edu/homestretchhackathon"
        },

//PROJECT RELEASES
        {   "type" :                  "Project Release",
            "label" :                 "Lemonade Stand 2.1 Released",
            "discipline" :            "Project Release",
            "date" :                  "2010-11-12",
            "relationship" :          "Project Release",
            "relationship-detail" :   "Version 2.1 of Lemonade Stand is released",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://blog.linkybook.com/2010/11/lemonade-stand-21-released.html"
        },
        {   "type" :                  "Project Release",
            "label" :                 "Blocku Released",
            "discipline" :            "Project Release",
            "date" :                  "2011-02-22",
            "relationship" :          "Project Release",
            "relationship-detail" :   "SugarLabs Activity Blocku is released",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://wiki.sugarlabs.org/go/Blocku"
        },
        {   "type" :                  "Project Release",
            "label" :                 "Mathematical Adventure: Fortune Hunter Released",
            "discipline" :            "Project Release",
            "date" :                  "2010-03-11",
            "relationship" :          "Project Release",
            "relationship-detail" :   "SugarLabs Activity Mathematical Adveture: Fortune Hunter is released",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://foss.rit.edu/projects/fortunehunter"
        },
        {   "type" :                  "Project Release",
            "label" :                 "Transbot Released",
            "discipline" :            "Project Release",
            "date" :                  "2010-11-06",
            "relationship" :          "Project Release",
            "relationship-detail" :   "IRC translation tool Transbot is released",
            "imageURL" :              "thoughts.png",
            "url" :                   "https://fedorahosted.org/transbot/"
        },
        {   "type" :                  "Project Release",
            "label" :                 "PacMath 2.0 Released",
            "discipline" :            "Project Release",
            "date" :                  "2010-02-25",
            "relationship" :          "Project Release",
            "relationship-detail" :   "SugarLabs Activity PacMath version 2.0 is released",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://wiki.sugarlabs.org/go/PacMath"
        },
        {   "type" :                  "Project Release",
            "label" :                 "OpenVideoChat Demo",
            "discipline" :            "Demo",
            "date" :                  "2010-03-10",
            "relationship" :          "Project Release",
            "relationship-detail" :   "OpenVideoChat proof of concept demo",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://foss.rit.edu/projects/ovc"
        },
        {   "type" :                  "Project Release",
            "label" :                 "Groovebot Released",
            "discipline" :            "Project Release",
            "date" :                  "2010-07-15",
            "relationship" :          "Project Release",
            "relationship-detail" :   "Groovebot: A Grooveshark IRC bot",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://gitorious.org/jlew/groovebot"
        },
        {   "type" :                  "Project Release",
            "label" :                 "MediaWiki Visualization",
            "discipline" :            "Demo",
            "date" :                  "2010-05-15",
            "relationship" :          "Project Release",
            "relationship-detail" :   "Visualization Demo of RITWiki",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://www.youtube.com/watch?v=Sau6l9TOhgk"
        },


//EVENTS
        {   "type" :                  "Event",
            "label" :                 "Digital Rochester Demo Night",
            "discipline" :            "Demo",
            "date" :                  "2011-11-01",
            "relationship" :          "Event",
            "relationship-detail" :   "Members of Digital Rochester came to see demonstrations from our students",
            "imageURL" :              "wrench.png",
            "url" :                   "http://beta.innovation.rit.edu/csi2/main/node/DigitalRochcester2011"
        },
        {   "type" :                  "Team Meeting",
            "label" :                 "Rochester Web Startups Walk-through",
            "discipline" :            "Team Meeting",
            "date" :                  "2011-11-28",
            "relationship" :          "Event",
            "relationship-detail" :   "Members of the Rochester Web Startups Meetup scouted our space for future meetings",
            "imageURL" :              "meeting.png",
            "url" :                   "http://www.meetup.com/Rochester-Web-Startups-Group/"
        },
        {   "type" :                  "Team Meeting",
            "label" :                 "StartupWeekendROC Committee Meeting",
            "discipline" :            "Team Meeting",
            "date" :                  "2012-01-11",
            "relationship" :          "Event",
            "relationship-detail" :   "Steering Committee Meeting for StartupWeekendROC",
            "imageURL" :              "meeting.png",
            "url" :                   "http://rochester.startupweekend.org"
        },
        {   "type" :                  "Team Meeting",
            "label" :                 "Hacks/HackersROC Committee Meeting",
            "discipline" :            "Team Meeting",
            "date" :                  "2012-01-09",
            "relationship" :          "Event",
            "relationship-detail" :   "Steering Committee Meeting between D&C, WXXI, and FOSS@RIT",
            "imageURL" :              "meeting.png",
            "url" :                   "http://www.meetup.com/HackshackersROC/"
        },
        {   "type" :                  "Team Meeting",
            "label" :                 "Hacks/HackersROC Kickoff Meeting",
            "discipline" :            "Team Meeting",
            "date" :                  "2012-01-15",
            "relationship" :          "Event",
            "relationship-detail" :   "Over 50 attendees, many of them real-life journalists, met at the CSI to talk future of news.",
            "imageURL" :              "meeting.png",
            "url" :                   "http://www.meetup.com/HackshackersROC/events/45260912/"
        },
        {   "type" :                  "Event",
            "label" :                 "Game-Mania @ Strong Museum of Play",
            "discipline" :            "Demo",
            "date" :                  "2011-11-05",
            "relationship" :          "Event",
            "relationship-detail" :   "Demo'd Educational Games developed for HFOSS course on the OLPC XO laptops",
            "imageURL" :              "Event.png",
            "url" :                   "http://games.rit.edu/videogamemania"
        },
        {   "type" :                  "Conference",
            "label" :                 "StartupWeekendSyracuse",
            "discipline" :            "Demo",
            "date" :                  "2011-11-04",
            "relationship" :          "Event",
            "relationship-detail" :   "Served as Technical Mentor, and Open Source Advisor",
            "imageURL" :              "Event.png",
            "url" :                   "http://syracuse.startupweekend.org"
        },
        {   "type" :                  "Event",
            "label" :                 "Google Faculty Research Program Info Session",
            "discipline" :            "Demo",
            "date" :                  "2011-07-15",
            "relationship" :          "Event",
            "relationship-detail" :   "Explored Future funding opportunities for FOSS@RIT",
            "imageURL" :              "Event.png",
            "url" :                   "http://research.google.com/university/relations/research_awards.html"
        },
        {   "type" :                  "Event",
            "label" :                 "SU Student Sandbox Demo Day",
            "discipline" :            "Demo",
            "date" :                  "2011-08-17",
            "relationship" :          "Event",
            "relationship-detail" :   "Tabled at SYR Tech Garden",
            "imageURL" :              "Event.png",
            "url" :                   "http://opensource.com/education/11/8/bridging-boxes-hacker-matchmaking-upstate-new-york-opensource-way"
        },
        {   "type" :                  "Event",
            "label" :                 "CIVX.us Monroe Elections Demo",
            "discipline" :            "Demo",
            "date" :                  "2010-11-02",
            "relationship" :          "Event",
            "relationship-detail" :   "Live CIVX.us Monroe Elections Demo for WXXI",
            "imageURL" :              "Event.png",
            "url" :                   "http://innovationtrail.org/post/election-night-results"
        },
        {   "type" :                  "Conference",
            "label" :                 "IEEE International Games Innovation Conference",
            "discipline" :            "Conference",
            "date" :                  "2011-11-04",
            "relationship" :          "Conference",
            "relationship-detail" :   "IEEE IGIC",
            "imageURL" :              "Event.png",
            "url" :                   "http://ice-gic.ieee-cesoc.org/2011/index.htm"
        },
        {   "type" :                  "Conference",
            "label" :                 "Audio Engineering Society Conference",
            "discipline" :            "Conference",
            "date" :                  "2011-10-24",
            "relationship" :          "Conference",
            "relationship-detail" :   "Game Audio Sessions",
            "imageURL" :              "Event.png",
            "url" :                   "http://www.gamasutra.com/view/news/38070/When_Motion_Controllers_And_Sound_Design_Collide.php"
        },
        {   "type" :                  "Conference",
            "label" :                 "RIT Undergrad Research Symposium - Best Paper in IT/Computing",
            "discipline" :            "Conference",
            "date" :                  "2011-08-12",
            "relationship" :          "Conference",
            "relationship-detail" :   "Nate Case won 'Best Paper in IT/Computing for his work on the CIVX project",
            "imageURL" :              "Event.png",
            "url" :                   "http://www.rit.edu/innovationcenter/symposium/News2010.html"
        },
        {   "type" :                  "Conference",
            "label" :                 "Open Source Software Research Mini-Summit",
            "discipline" :            "Conference",
            "date" :                  "2011-08-24",
            "relationship" :          "Conference",
            "relationship-detail" :   "Meeting of prominant FOSS labs internationally",
            "imageURL" :              "Event.png",
            "url" :                   "http://foss.rit.edu/files/Open_Source_Software_Research_Mini_Summit.pdf"
        },
        {   "type" :                  "Event",
            "label" :                 "RIT New Student Resource Fair",
            "discipline" :            "Demo",
            "date" :                  "2011-08-31",
            "relationship" :          "Event",
            "relationship-detail" :   "FOSS@RIT Tabled at event for incoming freshmen",
            "imageURL" :              "Event.png",
            "url" :                   "http://www.rit.edu/~w-orient/firstyear_highlights.php"
        },
        {   "type" :                  "Conference",
            "label" :                 "GOSCON - Government Open Source Conference",
            "discipline" :            "Conference",
            "date" :                  "2011-08-23",
            "relationship" :          "Conference",
            "relationship-detail" :   "Represented FOSS@RIT in Washington D.C.",
            "imageURL" :              "Event.png",
            "url" :                   "http://goscon.org/"
        },
        {   "type" :                  "Conference",
            "label" :                 "RIT Undergraduate Research Symposium",
            "discipline" :            "Conference",
            "date" :                  "2011-08-12",
            "relationship" :          "Conference",
            "relationship-detail" :   "Presentation of Student Research Projects",
            "imageURL" :              "Event.png",
            "url" :                   "http://www.rit.edu/innovationcenter/symposium/index.html"
        },
        {   "type" :                  "Conference",
            "label" :                 "ACM SIGITE",
            "discipline" :            "Conference",
            "date" :                  "2011-10-20",
            "relationship" :          "Conference",
            "relationship-detail" :   "IT Educators Panel",
            "imageURL" :              "Event.png",
            "url" :                   "http://opensource.com/education/11/10/foss-meets-it-education-acm-sigite"
        },
        {   "type" :                  "Conference",
            "label" :                 "Teaching Open Source Summit",
            "discipline" :            "Conference",
            "date" :                  "2010-10-29",
            "relationship" :          "Conference",
            "relationship-detail" :   "Teaching Open Source Summit",
            "imageURL" :              "Event.png",
            "url" :                   "http://teachingopensource.org/index.php/TOSS09"
        },
        {   "type" :                  "Conference",
            "label" :                 "HFOSS Symposium",
            "discipline" :            "Conference",
            "date" :                  "2010-03-10",
            "relationship" :          "Conference",
            "relationship-detail" :   "Humanitarian FOSS Project Symposium",
            "imageURL" :              "Event.png",
            "url" :                   "http://www.hfoss.org/hfoss2010/?q=node/10"
        },
        {   "type" :                  "Conference",
            "label" :                 "Frontiers in Education Conference",
            "discipline" :            "Conference",
            "date" :                  "2010-10-27",
            "relationship" :          "Conference",
            "relationship-detail" :   "Frontiers in Education Conference",
            "imageURL" :              "Event.png",
            "url" :                   "http://www.fie-conference.org/fie2010/Pages/letters.htm"
        },
        {   "type" :                  "Conference",
            "label" :                 "Personal Democracy Forum",
            "discipline" :            "Conference",
            "date" :                  "2010-06-05",
            "relationship" :          "Conference",
            "relationship-detail" :   "Personal Democracy Forum",
            "imageURL" :              "Event.png",
            "url" :                   "http://personaldemocracy.com/personal-democracy-forum-2010-conference-was"
        },
        {   "type" :                  "Conference",
            "label" :                 "IEEE Games Innovation Conference",
            "discipline" :            "Conference",
            "date" :                  "2010-12-21",
            "relationship" :          "Conference",
            "relationship-detail" :   "IEEE Games Innovation Conference",
            "imageURL" :              "Event.png",
            "url" :                   "http://ice-gic.ieee-cesoc.org/2011/index.htm"
        },
        {   "type" :                  "Conference",
            "label" :                 "NTID Technology Symposium",
            "discipline" :            "Conference",
            "date" :                  "2010-06-21",
            "relationship" :          "Conference",
            "relationship-detail" :   "NTID Technology Symposium",
            "imageURL" :              "Event.png",
            "url" :                   "http://www.rit.edu/ntid/vp/techsym/"
        },
        {   "type" :                  "Conference",
            "label" :                 "Engineer of the Future Conference",
            "discipline" :            "Conference",
            "date" :                  "2010-11-14",
            "relationship" :          "Conference",
            "relationship-detail" :   "Engineer of the Future Conference",
            "imageURL" :              "Event.png",
            "url" :                   "http://engineerofthefuture.illinois.edu/"
        },
        {   "type" :                  "Event",
            "label" :                 "ImagineRIT 2010",
            "discipline" :            "Event",
            "date" :                  "2010-05-01",
            "relationship" :          "Event",
            "relationship-detail" :   "ImagineRIT 2010",
            "imageURL" :              "Event.png",
            "url" :                   "http://www.rit.edu/imagine/"
        },
        {   "type" :                  "Conference",
            "label" :                 "RIT Summer Undergraduate Research Symposium",
            "discipline" :            "Conference",
            "date" :                  "2010-08-13",
            "relationship" :          "Conference",
            "relationship-detail" :   "RIT Summer Undergraduate Research Symposium",
            "imageURL" :              "Event.png",
            "url" :                   "http://www.rit.edu/innovationcenter/symposium/"
        },
        {   "type" :                  "Conference",
            "label" :                 "RIT Fall Undergraduate Research Symposium",
            "discipline" :            "Conference",
            "date" :                  "2010-11-12",
            "relationship" :          "Conference",
            "relationship-detail" :   "RIT Fall Undergraduate Research Symposium",
            "imageURL" :              "Event.png",
            "url" :                   "http://www.rit.edu/innovationcenter/symposium/"
        },
        {   "type" :                  "Conference",
            "label" :                 "Social Media and Communications Symposium",
            "discipline" :            "Conference",
            "date" :                  "2010-09-29",
            "relationship" :          "Conference",
            "relationship-detail" :   "Social Media and Communications Symposium",
            "imageURL" :              "Event.png",
            "url" :                   "http://www.rit.edu/cla/smacs/"
        },
        {   "type" :                  "Event",
            "label" :                 "POSSE @ RIT",
            "discipline" :            "Event",
            "date" :                  "2010-06-14",
            "relationship" :          "Event",
            "relationship-detail" :   "Professors' Open Source Summer Experience @ RIT",
            "imageURL" :              "Event.png",
            "url" :                   "http://teachingopensource.org/index.php/POSSE_RIT/2010"
        },
        {   "type" :                  "Conference",
            "label" :                 "FOSSCon 2010",
            "discipline" :            "Conference",
            "date" :                  "2010-06-19",
            "relationship" :          "Conference",
            "relationship-detail" :   "FOSSCon 2010 hosted @ RIT",
            "imageURL" :              "Event.png",
            "url" :                   "http://fosscon.org/"
        },
        {   "type" :                  "Event",
            "label" :                 "Walter Bender Lecture",
            "discipline" :            "Event",
            "date" :                  "2010-11-14",
            "relationship" :          "Event",
            "relationship-detail" :   "Walter Bender Lecture as a part of the Dean's Lecture Series in Golisano",
            "imageURL" :              "Event.png",
            "url" :                   "http://www.gccis.rit.edu/lecture-series"
        },
        {   "type" :                  "Event",
            "label" :                 "Richard Stallman Lecture",
            "discipline" :            "Event",
            "date" :                  "2010-02-23",
            "relationship" :          "Event",
            "relationship-detail" :   "FOSSCon 2010 hosted @ RIT",
            "imageURL" :              "Event.png",
            "url" :                   "http://www.rit.edu/innovationcenter/category/tags/csi"
        },
        {   "type" :                  "Event",
            "label" :                 "Righteous Pictures Screening and Workshop",
            "discipline" :            "Event",
            "date" :                  "2010-10-01",
            "relationship" :          "Event",
            "relationship-detail" :   "Righteous Pictures Screening and Workshop",
            "imageURL" :              "Event.png",
            "url" :                   "http://foss.rit.edu/events/righteouspictures"
        },
        {   "type" :                  "Event",
            "label" :                 "Software Freedom Day 2010",
            "discipline" :            "Event",
            "date" :                  "2010-09-18",
            "relationship" :          "Event",
            "relationship-detail" :   "Software Freedom Day 2010 @ RIT",
            "imageURL" :              "Event.png",
            "url" :                   "http://softwarefreedomday.org/"
        },
        {   "type" :                  "Conference",
            "label" :                 "CapitolCamp Developer Summit",
            "discipline" :            "Conference",
            "date" :                  "2010-08-19",
            "relationship" :          "Conference",
            "relationship-detail" :   "CapitolCamp Developer Summit",
            "imageURL" :              "Event.png",
            "url" :                   "http://barcamp.org/w/page/402087/CapitolCamp"
        },
        {   "type" :                  "Conference",
            "label" :                 "BarcampRoc Fall '10",
            "discipline" :            "Conference",
            "date" :                  "2010-10-23",
            "relationship" :          "Conference",
            "relationship-detail" :   "Barcamp Rochester Fall 2010",
            "imageURL" :              "Event.png",
            "url" :                   "http://barcamproc.org/"
        },
        {   "type" :                  "Event",
            "label" :                 "RIT48",
            "discipline" :            "Event",
            "date" :                  "2010-03-19",
            "relationship" :          "Event",
            "relationship-detail" :   "RIT48 Start-up Competition",
            "imageURL" :              "Event.png",
            "url" :                   "http://rit48.com/index_old.html"
        },
        {   "type" :                  "Event",
            "label" :                 "ARM Developer Day",
            "discipline" :            "Event",
            "date" :                  "2010-12-02",
            "relationship" :          "Event",
            "relationship-detail" :   "ARM Developer Day @ RIT",
            "imageURL" :              "Event.png",
            "url" :                   "http://afmiee.wordpress.com/"
        },
        {   "type" :                  "Event",
            "label" :                 "RITpedia Wikithon",
            "discipline" :            "Event",
            "date" :                  "2010-05-15",
            "relationship" :          "Event",
            "relationship-detail" :   "RITpedia Wikithon",
            "imageURL" :              "Event.png",
            "url" :                   "http://www.rit.edu/studentaffairs/ritpedia/wiki/Main_Page"
        },
        {   "type" :                  "Event",
            "label" :                 "InterlockROC & Co-working Rochester: Lightning Talks",
            "discipline" :            "Event",
            "date" :                  "2010-02-05",
            "relationship" :          "Event",
            "relationship-detail" :   "InterlockROC & Co-working Rochester: Lightning Talks",
            "imageURL" :              "Event.png",
            "url" :                   "http://www.rit.edu/innovationcenter/interlockroc-showcase-first-fridays-2510"
        },
        {   "type" :                  "Conference",
            "label" :                 "RIT Connectology Leadership Conference",
            "discipline" :            "Conference",
            "date" :                  "2011-04-09",
            "relationship" :          "Conference",
            "relationship-detail" :   "RIT Connectology Leadership Conference",
            "imageURL" :              "Event.png",
            "url" :                   "http://campuslife.rit.edu/leadership/connectology/conference.php"
        },
        {   "type" :                  "Hackathon",
            "label" :                 "FOSS@RIT Winter Hackfest",
            "discipline" :            "Hackathon",
            "date" :                  "2011-01-21",
            "relationship" :          "Hackathon",
            "relationship-detail" :   "FOSS@RIT Winter Hackfest",
            "imageURL" :              "Event.png",
            "url" :                   "http://foss.rit.edu/winterhackfest"
        },
        {   "type" :                  "Event",
            "label" :                 "InterlockROC Lightning Talks",
            "discipline" :            "Event",
            "date" :                  "2011-02-18",
            "relationship" :          "Event",
            "relationship-detail" :   "InterlockROC Lightning Talks",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://foss.rit.edu/events/InterlockROCLightningTalks"
        },
        {   "type" :                  "Conference",
            "label" :                 "PYCon: Connecting the Python Community",
            "discipline" :            "Conference",
            "date" :                  "2011-03-09",
            "relationship" :          "Conference",
            "relationship-detail" :   "PYCon: Connecting the Python Community",
            "imageURL" :              "Event.png",
            "url" :                   "http://us.pycon.org/2011/home/"
        },
        {   "type" :                  "Event",
            "label" :                 "Linux Installfest",
            "discipline" :            "Event",
            "date" :                  "2011-04-23",
            "relationship" :          "Event",
            "relationship-detail" :   "Linux Installfest",
            "imageURL" :              "Event.png",
            "url" :                   "http://installfest.org/"
        },
        {   "type" :                  "Hackathon",
            "label" :                 "FOSS@RIT Winter Wrap-up Hackathon",
            "discipline" :            "Hackathon",
            "date" :                  "2011-02-18",
            "relationship" :          "Hackathon",
            "relationship-detail" :   "FOSS@RIT Winter Wrap-up Hackathon",
            "imageURL" :              "hackfest.png",
            "url" :                   "http://foss.rit.edu/WWH"
        },
        {   "type" :                  "Event",
            "label" :                 "FOSS@RIT Spring Opportunities Meeting",
            "discipline" :            "Event",
            "date" :                  "2011-03-09",
            "relationship" :          "Event",
            "relationship-detail" :   "FOSS@RIT Spring Opportunities Meeting",
            "imageURL" :              "Event.png",
            "url" :                   "http://foss.rit.edu/spring2011"
        },
        {   "type" :                  "Conference",
            "label" :                 "BarcampRoc Spring '11",
            "discipline" :            "Conference",
            "date" :                  "2011-04-16",
            "relationship" :          "Conference",
            "relationship-detail" :   "Spring 2011 Barcamp Rochester",
            "imageURL" :              "Event.png",
            "url" :                   "http://www.barcamproc.org/"
        },
        {   "type" :                  "Event",
            "label" :                 "GCCIS Undergrad Research Fellowship Application/Doc Sprint",
            "discipline" :            "Event",
            "date" :                  "2011-03-21",
            "relationship" :          "Event",
            "relationship-detail" :   "GCCIS Undergrad Research Fellowship Application/Doc Sprint",
            "imageURL" :              "Event.png",
            "url" :                   "http://foss.rit.edu/summer-research-app-sprint"
        },
        {   "type" :                  "Event",
            "label" :                 "StackOverflow Meetup",
            "discipline" :            "Event",
            "date" :                  "2011-04-06",
            "relationship" :          "Event",
            "relationship-detail" :   "StackOverflow Meetup",
            "imageURL" :              "Event.png",
            "url" :                   "http://blog.stackoverflow.com/2011/03/stack-overflow-meetups-april-6/"
        },
        {   "type" :                  "Event",
            "label" :                 "EdTechDay",
            "discipline" :            "Event",
            "date" :                  "2011-03-24",
            "relationship" :          "Event",
            "relationship-detail" :   "EdTechDay",
            "imageURL" :              "Event.png",
            "url" :                   "http://www.ithaca.edu/edtechday"
        },
        {   "type" :                  "Conference",
            "label" :                 "TEDxBuffalo 2011",
            "discipline" :            "Conference",
            "date" :                  "2011-10-11",
            "relationship" :          "Conference",
            "relationship-detail" :   "TEDxBuffalo",
            "imageURL" :              "Event.png",
            "url" :                   "http://bit.ly/tedxbuffalo-civx"
        },
        {   "type" :                  "Conference",
            "label" :                 "WeLiveNYSummit 2011",
            "discipline" :            "Conference",
            "date" :                  "2011-03-26",
            "relationship" :          "Conference",
            "relationship-detail" :   "WeLiveNYSummit 2011 - Transparency, Technology, and Gov2.0",
            "imageURL" :              "Event.png",
            "url" :                   "http://unystartups.com/2011/03/22/promotional-video-we-live-ny-summit-2011/"
        },
        {   "type" :                  "Event",
            "label" :                 "Rochester Java User Group Meeting (RJUG)",
            "discipline" :            "Event",
            "date" :                  "2011-04-15",
            "relationship" :          "Event",
            "relationship-detail" :   "Rochester Java User Group Meeting (RJUG)",
            "imageURL" :              "Event.png",
            "url" :                   "http://foss.rit.edu/node/283"
        },
        {   "type" :                  "Hackathon",
            "label" :                 "RiseAboveTheCrowd Hackfest",
            "discipline" :            "Hackathon",
            "date" :                  "2011-04-27",
            "relationship" :          "Hackathon",
            "relationship-detail" :   "RiseAboveTheCrowd Hackfest",
            "imageURL" :              "hackfest.png",
            "url" :                   "http://foss.rit.edu/node/290"
        },
        {   "type" :                  "Event",
            "label" :                 "ImagineRIT",
            "discipline" :            "Event",
            "date" :                  "2011-05-07",
            "relationship" :          "Event",
            "relationship-detail" :   "ImagineRIT",
            "imageURL" :              "Event.png",
            "url" :                   "http://www.rit.edu/imagine/"
        },
        {   "type" :                  "Conference",
            "label" :                 "BarcampROC Fall '11",
            "discipline" :            "Conference",
            "date" :                  "2011-10-22",
            "relationship" :          "Conference",
            "relationship-detail" :   "BarcampROC Fall 2011",
            "imageURL" :              "Event.png",
            "url" :                   "http://BarcampROC.org"
        },
        {   "type" :                  "Event",
            "label" :                 "FOSS@RIT Breakfast Send-off",
            "discipline" :            "Event",
            "date" :                  "2011-05-19",
            "relationship" :          "Event",
            "relationship-detail" :   "FOSS@RIT Breakfast Send-off",
            "imageURL" :              "Event.png",
            "url" :                   "http://foss.rit.edu/node/296"
        },
        {   "type" :                  "Event",
            "label" :                 "FOSS@RIT Summer Undergraduate Research Fellowship Kick-Off",
            "discipline" :            "Event",
            "date" :                  "2011-04-27",
            "relationship" :          "Event",
            "relationship-detail" :   "FOSS@RIT Summer Undergraduate Research Fellowship Kick-Off",
            "imageURL" :              "Event.png",
            "url" :                   "http://foss.rit.edu/node/297"
        },
        {   "type" :                  "Event",
            "label" :                 "StartupROC Meeting",
            "discipline" :            "Event",
            "date" :                  "2011-06-07",
            "relationship" :          "Event",
            "relationship-detail" :   "StartupROC Meeting",
            "imageURL" :              "Event.png",
            "url" :                   "http://startupweekend.org/"
        },
        {   "type" :                  "Hackathon",
            "label" :                 "FOSS@RIT POSSE Hackathon",
            "discipline" :            "Hackathon",
            "date" :                  "2011-06-06",
            "relationship" :          "Hackathon",
            "relationship-detail" :   "FOSS@RIT POSSE Hackathon",
            "imageURL" :              "hackfest.png",
            "url" :                   "http://teachingopensource.org/index.php/POSSE_RIT"
        },
        {   "type" :                  "Event",
            "label" :                 "FOSS@RIT & SU Student Sandbox Hackathon",
            "discipline" :            "Event",
            "date" :                  "2011-07-12",
            "relationship" :          "Event",
            "relationship-detail" :   "FOSS@RIT & SU Student Sandbox Hackathon",
            "imageURL" :              "Event.png",
            "url" :                   "http://www.syracusestudentsandbox.com/"
        },
        {   "type" :                  "Event",
            "label" :                 "POSSE",
            "discipline" :            "Event",
            "date" :                  "2011-07-14",
            "relationship" :          "Event",
            "relationship-detail" :   "POSSE",
            "imageURL" :              "Event.png",
            "url" :                   "http://teachingopensource.org/index.php/POSSE_RIT"
        },
    ]
}
