{
    "types" : {
        "Contributor" : {
            pluralLabel: "Contributors",
        "Press" : {
            pluralLabel: "Press",
        "Team Meeting" : {
            pluralLabel: "Team Meetings",
        "Dev Meeting" : {
            pluralLabel: "Dev Meetings",
        "Design Meeting" : {
            pluralLabel: "Design Meetings",
        "Test Event" : {
            pluralLabel: "Test Events",
        "Event" : {
            pluralLabel: "Events",
        "Hackathon" : {
            pluralLabel: "Hackathons",
		"Project Release" : {
			pluralLabel: "Project Releases"
		}
        }
        }
        }
        }
        }
        }
        }
        }
    },
    "properties": {
        "person" : {
            "valueType" : "item"
        }
    },
    "items" : [
        {   "type" :                  "Contributor",
            "label" :                 "Michael Riordan",
            "department" :            "Print Media",
            "discipline" :            "Publishing",
            "last-name" :             "Riordan",
            "date" :                  "2010-06",
            "role" :                  "Director",
            "relationship-detail" :   "Mentor and Product Owner",
            "url" :                   "http://opl.rit.edu",
            "person" :                "Michael Riordan",
            "imageURL" :              "person.png",
        },
        {   "type" :                  "Contributor",
            "label" :                 "Matthew Bernius",
            "department" :            "Multi-Disciplinary Studies",
            "discipline" :            "Publishing",
            "last-name" :             "Bernius",
            "date" :                  "2010-06",
            "role" :                  "Mentor",
            "relationship-detail" :   "Developer and Future Mentor",
            "url" :                   "http://www.mattbernius.com",
            "person" :                "Matthew Bernius",
            "imageURL" :              "person.png",
        },
        {   "type" :                  "Contributor",
            "label" :                 "John Karahalis",
            "department" :            "Computing & Information Sciences",
            "discipline" :            "Lead Developer",
            "last-name" :             "Karahalis",
            "date" :                  "2010-06",
            "role" :                  "Lead Developer & Scrum Master",
            "major" :                 "Computer Science",
            "relationship-detail" :   "Theming, Modules, Site",
            "url" :                   "http://opl.rit.edu/researchers/current-students/john-karahalis/",
            "person" :                "John Karahalis",
            "imageURL" :              "person.png",
        },
        {   "type" :                  "Contributor",
            "label" :                 "Mark Newell",
            "department" :            "Open Publishing Lab",
            "discipline" :            "Developer",
            "shared" :                "no",
            "last-name" :             "Newell",
            "date" :                  "2010-06",
            "role" :                  "Drupal Developer",
            "relationship-detail" :   "Theming and Development, Co-op with Rochester Democrat & Chronicle",
            "url" :                   "http://www.markofthenewells.com",
            "person" :                "Mark Newell",
            "imageURL" :              "person.png",
        },
        {   "type" :                  "Contributor",
            "label" :                 "Remy DeCausemaker",
            "department" :            "Lab for Technological Literacy",
            "discipline" :            "Hactivist & Storyteller",
            "last-name" :             "DeCausemaker",
            "date" :                  "2010-06",
            "role" :                  "Storyteller",
            "relationship-detail" :   "Facilitation of Meetings and Development. Touchstone for each discipline, for each team",
            "url" :                   "http://foss.rit.edu/blog/decause",
            "person" :                "Remy DeCausemaker",
            "imageURL" :              "person.png",
        },
        {   "type" :                  "Contributor",
            "label" :                 "Stephen Jacobs",
            "department" :            "Lab for Technological Literacy",
            "discipline" :            "Interactive Games & Media",
            "last-name" :             "Jacobs",
            "date" :                  "2010-06",
            "role" :                  "Mentor",
            "relationship-detail" :   "Faculty Advisor of FOSS@RIT, Professor of Interactive Games & Media",
            "url" :                   "http://gryphonscratches.blogspot.com",
            "person" :                "Stephen Jacobs",
            "imageURL" :              "person.png",
        },
        {   "type" :                  "Contributor",
            "label" :                 "Vic Perotti",
            "department" :            "Business",
            "discipline" :            "Digital Entrepreneurship",
            "last-name" :             "Perotti",
            "date" :                  "2010-06",
            "role" :                  "Mentor",
            "relationship-detail" :   "Professor RIT College of Business, Champion of Digital Business",
            "url" :                   "http://www.perotti.com",
            "person" :                "Vic Perotti",
            "imageURL" :              "person.png",
        },
        {   "type" :                  "Contributor",
            "label" :                 "Andrea Hickerson",
            "department" :            "Communication",
            "discipline" :            "Journalism",
            "last-name" :             "Hickerson",
            "date" :                  "2010-06",
            "role" :                  "Mentor",
            "relationship-detail" :   "Professor RIT Department of Communication",
            "url" :                   "http://andreahickerson.blogspot.com",
            "person" :                "Andrea Hickerson",
            "imageURL" :              "person.png",
        },
        {   "type" :                  "Contributor",
            "label" :                 "Jaclyn Donner",
            "department" :            "Imaging Arts & Sciences",
            "discipline" :            "Graphic Design",
            "last-name" :             "Donner",
            "date" :                  "2010-11",
            "role" :                  "Designer",
            "major" :                 "Graphic Design",
            "relationship-detail" :   "Jackie Designed everything from our Logos, to our icons and T-Shirts. She is a rockstar",
            "url" :                   "http://jackiedonner.tumblr.com",
            "person" :                "Jaclyn Donner",
            "imageURL" :              "person.png",
        },
        {   "type" :                  "Contributor",
            "label" :                 "Mark DeMayo",
            "department" :            "FOSS@RIT",
            "discipline" :            "Developer/Designer",
            "last-name" :             "DeMayo",
            "date" :                  "2010-11",
            "role" :                  "Developer/Designer",
            "major" :                 "Game Design",
            "relationship-detail" :   "One of our few front-end devs with Drupal chops, Mark served as lynchpin for the design and dev team.",
            "url" :                   "http://people.rit.edu/~mxd6823",
            "person" :                "Mark DeMayo",
            "imageURL" :              "person.png",
        },
        {   "type" :                  "Contributor",
            "label" :                 "Ariel Zamparini",
            "department" :            "FOSS@RIT",
            "discipline" :            "Developer",
            "last-name" :             "Zamparini",
            "date" :                  "2010-11",
            "role" :                  "Drupal Developer",
            "major" :                 "Game Design",
            "relationship-detail" :   "Working primarily in the back-end and module research, Ariel helped when he could.",
            "url" :                   "http://arielzamparini.com",
            "person" :                "Ariel Zamparini",
            "imageURL" :              "person.png",
        },
        {   "type" :                  "Contributor",
            "label" :                 "Ben Vanderberg",
            "department" :            "Imaging Arts & Sciences",
            "discipline" :            "Interaction Design",
            "last-name" :             "Vanderberg",
            "date" :                  "2011-03",
            "role" :                  "Designer",
            "major" :                 "New Media Publishing",
            "relationship-detail" :   "Ben's firm grasp of UI, web design, and Graffle was a boon to the Design team.",
            "url" :                   "http://www.benvanderberg.com",
            "person" :                "Ben Vanderberg",
            "imageURL" :              "person.png",
        },
        {   "type" :                  "Contributor",
            "label" :                 "Dustin Wright",
            "department" :            "Imaging Arts & Sciences",
            "discipline" :            "Graphic Design",
            "last-name" :             "Wright",
            "date" :                  "2011-03",
            "major" :                 "New Media Publishing",
            "role" :                  "Designer",
            "relationship-detail" :   "Dustin coordinated typography with Jackie, and produced many a mockup",
            "url" :                   "http://www.linkedin.com/pub/dustin-wright/1a/12a/257",
            "person" :                "Dustin Wright",
            "imageURL" :              "person.png",
        },
        {   "type" :                  "Contributor",
            "label" :                 "Matt Rogers",
            "department" :            "Computing & Information Sciences",
            "discipline" :            "Developer/Designer",
            "last-name" :             "Rogers",
            "date" :                  "2011-02",
            "role" :                  "Developer/Designer",
            "major" :                 "Computer Science",
            "relationship-detail" :   "Straddling the line between designer and developer, Matt provided great design and implementation insights.",
            "url" :                   "http://matthewdrogers.com",
            "person" :                "Matt Rogers",
            "imageURL" :              "person.png",
        },
        {   "type" :                  "Contributor",
            "label" :                 "Josef Patoprsty",
            "department" :            "Computing & Information Sciences",
            "discipline" :            "Developer",
            "last-name" :             "Patoprsty",
            "date" :                  "2011-02",
            "role" :                  "Drupal Developer",
            "Major" :                 "Computer Science",
            "relationship-detail" :   "A rock-solid PHP/Drupal Developer, Serious Heavy-lifter, and OPL Veteran.",
            "url" :                   "http://imaginerit.ytmnd.com",
            "person" :                "Josef Patoprsty",
            "imageURL" :              "person.png",
        },
        {   "type" :                  "Contributor",
            "label" :                 "Guy Paddock",
            "department" :            "Consultant - Red Bottle",
            "discipline" :            "Developer",
            "last-name" :             "Paddock",
            "date" :                  "2011-03",
            "role" :                  "Drupal Developer",
            "relationship-detail" :   "Guy worked on the original Inew Platform. His familiarity with the code truly helped during crunch-time",
            "url" :                   "https://twitter.com/#!/guypaddock",
            "person" :                "Guy Paddock",
            "imageURL" :              "person.png",
        },
        {   "type" :                  "Contributor",
            "label" :                 "Nathaniel Case",
            "department" :            "FOSS@RIT",
            "discipline" :            "Developer/Designer",
            "last-name" :             "Case",
            "date" :                  "2011-03",
            "role" :                  "Developer/Designer",
            "major" :                 "Computer Science",
            "relationship-detail" :   "Nate is an all-aroud Hacker. Front-end or back-end, he picked up serious slack and filled in where needed.",
            "url" :                   "http://whynotwingnut.blogspot.com",
            "person" :                "Nate Case",
            "imageURL" :              "person.png",
        },
        {   "type" :                  "Contributor",
            "label" :                 "Alex Gentile",
            "department" :            "Consultant - Red Bottle",
            "discipline" :            "Developer",
            "last-name" :             "Gentile",
            "date" :                  "2011-03",
            "role" :                  "Drupal Developer",
            "relationship-detail" :   "Alex was instrumental in the administration and deployment of the RiseAboveTheCrowd platform.",
            "url" :                   "https://twitter.com/#!/AlexGentile",
            "person" :                "Alex Gentile",
            "imageURL" :              "person.png",
        },




//HACKATHONS
		{   "type" :                  "Hackathon",
            "label" :                 "CrisisCampRoc Hackathon for Haiti",
            "discipline" :            "Hackathon",
            "date" :                  "2010-02-12",
            "relationship" :            "Hackathon",
            "relationship-detail" :   "Hackathon for Haiti relief",
            "imageURL" :              "hackfest.png",
            "url" :                   "http://www.rit.edu/innovationcenter/crisiscamproc-hack-thon-haiti-follow"
        },
		{   "type" :                  "Hackathon",
            "label" :                 "Sunlight Foundation's Great American Hackathon",
            "discipline" :            "Hackathon",
            "date" :                  "2009-12-12",
            "relationship" :            "Hackathon",
            "relationship-detail" :   "RIT's local hackathon as a part of the Great American Hackathon event",
            "imageURL" :              "hackfest.png",
            "url" :                   "http://www.rit.edu/innovationcenter/great-american-hackathon-rit"
        },
		{   "type" :                  "Hackathon",
            "label" :                 "FOSS@RIT OLPC HQ Hackathon",
            "discipline" :            "Hackathon",
            "date" :                  "2010-07-28",
            "relationship" :            "Hackathon",
            "relationship-detail" :   "FOSS@RIT goes to OLPC HQ!",
            "imageURL" :              "hackfest.png",
            "url" :                   "http://www.rit.edu/innovationcenter/category/tags/hackathon"
        },
		{   "type" :                  "Hackathon",
            "label" :                 "FOSS@RIT Homestretch Hackathon Summer",
            "discipline" :            "Hackathon",
            "date" :                  "2010-08-04",
            "relationship" :            "Hackathon",
            "relationship-detail" :   "FOSS@RIT Homestretch Hackathon",
            "imageURL" :              "hackfest.png",
            "url" :                   "http://foss.rit.edu/homestretchhackathon"
        },

//PROJECT RELEASES
		{   "type" :                  "Project Release",
            "label" :                 "Lemonade Stand 2.1 Released",
            "discipline" :            "Project Release",
            "date" :                  "2010-11-12",
            "relationship" :          "Project Release",
            "relationship-detail" :   "Version 2.1 of Lemonade Stand is released",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://blog.linkybook.com/2010/11/lemonade-stand-21-released.html"
        },
		{   "type" :                  "Project Release",
            "label" :                 "Blocku Released",
            "discipline" :            "Project Release",
            "date" :                  "2011-02-22",
            "relationship" :          "Project Release",
            "relationship-detail" :   "SugarLabs Activity Blocku is released",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://wiki.sugarlabs.org/go/Blocku"
        },
		{   "type" :                  "Project Release",
            "label" :                 "Mathematical Adventure: Fortune Hunter Released",
            "discipline" :            "Project Release",
            "date" :                  "2010-03-11",
            "relationship" :          "Project Release",
            "relationship-detail" :   "SugarLabs Activity Mathematical Adveture: Fortune Hunter is released",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://foss.rit.edu/projects/fortunehunter"
        },
		{   "type" :                  "Project Release",
            "label" :                 "Transbot Released",
            "discipline" :            "Project Release",
            "date" :                  "2010-11-06",
            "relationship" :          "Project Release",
            "relationship-detail" :   "IRC translation tool Transbot is released",
            "imageURL" :              "thoughts.png",
            "url" :                   "https://fedorahosted.org/transbot/"
        },
		{   "type" :                  "Project Release",
            "label" :                 "PacMath 2.0 Released",
            "discipline" :            "Project Release",
            "date" :                  "2010-02-25",
            "relationship" :          "Project Release",
            "relationship-detail" :   "SugarLabs Activity PacMath version 2.0 is released",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://wiki.sugarlabs.org/go/PacMath#License"
        },
		{   "type" :                  "Project Release",
            "label" :                 "OpenVideoChat Demo",
            "discipline" :            "Demo",
            "date" :                  "2010-03-10",
            "relationship" :          "Project Release",
            "relationship-detail" :   "OpenVideoChat proof of concept demo",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://foss.rit.edu/projects/ovc"
        },
		{   "type" :                  "Project Release",
            "label" :                 "Groovebot Released",
            "discipline" :            "Project Release",
            "date" :                  "2010-07-15",
            "relationship" :          "Project Release",
            "relationship-detail" :   "Groovebot: A Grooveshark IRC bot",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://gitorious.org/jlew/groovebot"
        },
		{   "type" :                  "Project Release",
            "label" :                 "MediaWiki Visualization",
            "discipline" :            "Demo",
            "date" :                  "2010-05-15",
            "relationship" :          "Project Release",
            "relationship-detail" :   "Visualization Demo of RITWiki",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://www.youtube.com/watch?v=Sau6l9TOhgk"
        },


//EVENTS
        {   "type" :                  "Event",
            "label" :                 "CIVX.us Monroe Elections Demo",
            "discipline" :            "Demo",
            "date" :                  "2010-11-02",
            "relationship" :          "Event",
            "relationship-detail" :   "Live CIVX.us Monroe Elections Demo for WXXI",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://innovationtrail.org/post/election-night-results"
        },
		{   "type" :                  "Event",
            "label" :                 "Teaching Open Source Summit",
            "discipline" :            "Event",
            "date" :                  "2010-10-29",
            "relationship" :          "Event",
            "relationship-detail" :   "Teaching Open Source Summit",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://teachingopensource.org/index.php/TOSS09"
        },
		{   "type" :                  "Event",
            "label" :                 "HFOSS Symposium",
            "discipline" :            "Event",
            "date" :                  "2010-03-10",
            "relationship" :          "Event",
            "relationship-detail" :   "Humanitarian FOSS Project Symposium",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://www.hfoss.org/hfoss2010/?q=node/10"
        },
		{   "type" :                  "Event",
            "label" :                 "Frontiers in Education Conference",
            "discipline" :            "Event",
            "date" :                  "2010-10-27",
            "relationship" :          "Event",
            "relationship-detail" :   "Frontiers in Education Conference",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://www.fie-conference.org/fie2010/Pages/letters.htm"
        },
		{   "type" :                  "Event",
            "label" :                 "Personal Democracy Forum",
            "discipline" :            "Event",
            "date" :                  "2010-06-05",
            "relationship" :          "Event",
            "relationship-detail" :   "Personal Democracy Forum",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://personaldemocracy.com/personal-democracy-forum-2010-conference-was"
        },
		{   "type" :                  "Event",
            "label" :                 "IEEE Games Innovation Conference",
            "discipline" :            "Event",
            "date" :                  "2010-12-21",
            "relationship" :          "Event",
            "relationship-detail" :   "IEEE Games Innovation Conference",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://ice-gic.ieee-cesoc.org/2011/index.htm"
        },
		{   "type" :                  "Event",
            "label" :                 "NTID Technology Symposium",
            "discipline" :            "Event",
            "date" :                  "2010-06-21",
            "relationship" :          "Event",
            "relationship-detail" :   "NTID Technology Symposium",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://www.rit.edu/ntid/vp/techsym/"
        },
		{   "type" :                  "Event",
            "label" :                 "Engineer of the Future Conference",
            "discipline" :            "Event",
            "date" :                  "2010-11-14",
            "relationship" :          "Event",
            "relationship-detail" :   "Engineer of the Future Conference",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://engineerofthefuture.illinois.edu/"
        },
		{   "type" :                  "Event",
            "label" :                 "ImagineRIT 2010",
            "discipline" :            "Event",
            "date" :                  "2010-05-01",
            "relationship" :          "Event",
            "relationship-detail" :   "ImagineRIT 2010",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://www.rit.edu/imagine/"
        },
		{   "type" :                  "Event",
            "label" :                 "RIT Summer Undergraduate Research Symposium",
            "discipline" :            "Event",
            "date" :                  "2010-08-13",
            "relationship" :          "Event",
            "relationship-detail" :   "RIT Summer Undergraduate Research Symposium",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://www.rit.edu/innovationcenter/symposium/"
        },
		{   "type" :                  "Event",
            "label" :                 "RIT Fall Undergraduate Research Symposium",
            "discipline" :            "Event",
            "date" :                  "2010-11-12",
            "relationship" :          "Event",
            "relationship-detail" :   "RIT Fall Undergraduate Research Symposium",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://www.rit.edu/innovationcenter/symposium/"
        },
		{   "type" :                  "Event",
            "label" :                 "Social Media and Communications Symposium",
            "discipline" :            "Event",
            "date" :                  "2010-09-29",
            "relationship" :          "Event",
            "relationship-detail" :   "Social Media and Communications Symposium",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://www.rit.edu/cla/smacs/"
        },
		{   "type" :                  "Event",
            "label" :                 "POSSE @ RIT",
            "discipline" :            "Event",
            "date" :                  "2010-06-14",
            "relationship" :          "Event",
            "relationship-detail" :   "Professors' Open Source Summer Experience @ RIT",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://teachingopensource.org/index.php/POSSE_RIT/2010"
        },
		{   "type" :                  "Event",
            "label" :                 "FOSSCon 2010",
            "discipline" :            "Event",
            "date" :                  "2010-06-19",
            "relationship" :          "Event",
            "relationship-detail" :   "FOSSCon 2010 hosted @ RIT",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://fosscon.org/"
        },
		{   "type" :                  "Event",
            "label" :                 "Walter Bender Lecture",
            "discipline" :            "Event",
            "date" :                  "2010-11-14",
            "relationship" :          "Event",
            "relationship-detail" :   "Walter Bender Lecture as a part of the Dean's Lecture Series in Golisano",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://www.gccis.rit.edu/lecture-series"
        },
		{   "type" :                  "Event",
            "label" :                 "Richard Stallman Lecture",
            "discipline" :            "Event",
            "date" :                  "2010-02-23",
            "relationship" :          "Event",
            "relationship-detail" :   "FOSSCon 2010 hosted @ RIT",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://www.rit.edu/innovationcenter/category/tags/csi"
        },
		{   "type" :                  "Event",
            "label" :                 "Righteous Pictures Screening and Workshop",
            "discipline" :            "Event",
            "date" :                  "2010-10-01",
            "relationship" :          "Event",
            "relationship-detail" :   "Righteous Pictures Screening and Workshop",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://foss.rit.edu/events/righteouspictures"
        },
		{   "type" :                  "Event",
            "label" :                 "Software Freedom Day 2010",
            "discipline" :            "Event",
            "date" :                  "2010-09-18",
            "relationship" :          "Event",
            "relationship-detail" :   "Software Freedom Day 2010 @ RIT",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://softwarefreedomday.org/"
        },
		{   "type" :                  "Event",
            "label" :                 "CapitolCamp Developer Summit",
            "discipline" :            "Event",
            "date" :                  "2010-08-19",
            "relationship" :          "Event",
            "relationship-detail" :   "CapitolCamp Developer Summit",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://barcamp.org/w/page/402087/CapitolCamp"
        },
		{   "type" :                  "Event",
            "label" :                 "Barcamp Rochester",
            "discipline" :            "Event",
            "date" :                  "2010-10-23",
            "relationship" :          "Event",
            "relationship-detail" :   "Barcamp Rochester",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://barcamproc.org/"
        },
		{   "type" :                  "Event",
            "label" :                 "RIT48",
            "discipline" :            "Event",
            "date" :                  "2010-03-19",
            "relationship" :          "Event",
            "relationship-detail" :   "RIT48 Start-up Competition",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://rit48.com/index_old.html"
        },
		{   "type" :                  "Event",
            "label" :                 "ARM Developer Day",
            "discipline" :            "Event",
            "date" :                  "2010-12-02",
            "relationship" :          "Event",
            "relationship-detail" :   "ARM Developer Day @ RIT",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://afmiee.wordpress.com/"
        },
		{   "type" :                  "Event",
            "label" :                 "RITpedia Wikithon",
            "discipline" :            "Event",
            "date" :                  "2010-05-15",
            "relationship" :          "Event",
            "relationship-detail" :   "RITpedia Wikithon",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://www.rit.edu/studentaffairs/ritpedia/wiki/Main_Page"
        },
		{   "type" :                  "Event",
            "label" :                 "InterlockROC & Co-working Rochester: Lightning Talks",
            "discipline" :            "Event",
            "date" :                  "2010-02-05",
            "relationship" :          "Event",
            "relationship-detail" :   "InterlockROC & Co-working Rochester: Lightning Talks",
            "imageURL" :              "thoughts.png",
            "url" :                   "http://www.rit.edu/innovationcenter/interlockroc-showcase-first-fridays-2510"
        },
    ]
}
